- .eslintrc.json
- .github/workflows/code-ql.yml
- .github/workflows/node-ci.yml
- .gitignore
- .prettierrc
- package-lock.json
- package.json
- src/index.ts
- tsconfig.json
Sets up the standard infrastructure for the project.
Closes #XXXXX
> feat: initial project infrastructure

- package-lock.json
- package.json
- sample.env
- src/commands/CommandList.ts
- src/commands/setup.ts
- src/config/IntentOptions.ts
- src/config/QuoteList.ts
- src/database/connectDatabase.ts
- src/database/models/Inspiration.ts
- src/index.ts
- src/interfaces/Command.ts
- src/interfaces/Quote.ts
- src/modules/generateQuoteEmbed.ts
- src/modules/getDateStamp.ts
- src/modules/scheduleInspiration.ts
- src/modules/validateEnv.ts
- src/utils/errorHandler.ts
- src/utils/logHandler.ts
- src/utils/registerCommands.ts
Sets up the initial attempt at the bot.
Closes #XXXXX
> feat: initial bot prototype

- src/config/QuoteList.ts
Add quote.
```
Whether you think you can, or you think you can’t – you’re right.
- Henry Ford
```
n/a
> docs: add quote

- src/config/QuoteList.ts
> Added 2 quotes to QuoteList.ts

- src/config/QuoteList.ts
Added the quote "What you think, you become. What you feel, you attract. What you imagine, you create."
Closes #XXXXX
> quote added

- src/config/QuoteList.ts
> quotes added

- src/config/QuoteList.ts
> Added one Quote 

- src/config/QuoteList.ts
> Mr. Miyagi Quote

- src/config/QuoteList.ts
> added Antoine de Saint-Exupery's quote

- src/config/QuoteList.ts
Added two quotes to the array from Otto Von Bismarck and Guion Bluford
> added quotes from Otto Von Bismarck and Guion Bluford

- src/config/QuoteList.ts
I added quotes by Barack Obama, West and Robert Frost
Closes #XXXXX
> added quotes by Barack Obama, Mae West & Robert Frost

- package-lock.json
- package.json
- test/quotes.spec.ts
- tsconfig.json
Adds a test for quotes that appear to be similar.
Closes #XXXXX
> feat: test for similar quotes

- .vscode/settings.json
- src/config/QuoteList.ts
One quote was added to add variety to the quotes.
> Steinbeck quote added to QuoteList

- src/config/QuoteList.ts
added 6 new quotes to QuoteList.ts
> new-quotes-kc

- src/config/QuoteList.ts
> Adding quote from Doctor Who

- src/config/QuoteList.ts
> A quote by Muhammad Ali

- src/config/QuoteList.ts
> quote by Eminem

- src/config/QuoteList.ts
I have added three more quotes in QuoteList.ts. Kindly review the changes
> Added more quotes to QuoteList.ts

- src/config/QuoteList.ts
Added 5 quotes to QuoteList.ts, 4 from Thomas Edison and 1 from Danny Thompson
The quotes are pushed into the QuoteList Array from index QuoteList.length - 1 as per contribution guidelines. The quotes I chose from Thomas Edison, which I am familiar with, are most relatable to every software developer. I also did not see Danny's ABL ABB CCC quote added yet to the list.
> Added 5 quotes to QuoteList.ts

- src/config/QuoteList.ts
Signed-off-by: iamxxx777 <iamxxx333@gmail.com>
This pull request adds 3 new quotes to the quotes list. One quote from Usain bolt, one from Jeanette Walls and another from C.S. Lewis. All test passed before the pull request was made.
> Added 3 new quotes to the Quote List

- src/config/QuoteList.ts
> Added Quote

- src/config/QuoteList.ts
Signed-off-by: Williams Samuel <samwill300@gmail.com>
Added new Quote to the QuoteList.ts file
> added new quote to the QuoteList file

- src/config/QuoteList.ts
Hey @nhcarrigan, I added 19 more quotes to the QuoteList.ts file. Please have a look.
> Added 19 more quotes

- src/config/QuoteList.ts
> Adding Lao Tzu Quotes

- src/config/QuoteList.ts
> Updated quotse

- src/config/QuoteList.ts
Signed-off-by: Williams Samuel <samwill300@gmail.com>
Added five new quotes
> added five new quotes to the QuoteList file

- src/config/QuoteList.ts
To add quote to Quotelist.tx
Added a quote by Mother Teresa
Closes #XXXXX
> Added Mother Teresa quote

- src/config/QuoteList.ts
Added 5 quotes to QuoteList.ts
Not an issue but added these according to your call on the "Commit Your Code" discord server.
Closes #XXXXX
> Adding 5 quotes

- src/config/QuoteList.ts
I added 3 new quotes from Walt Disney, Josh S Hinds and James Butler Yeats to the QuoteList.ts
None
> Added 3 new quotes

- src/config/QuoteList.ts
> added one Dr. Dre quote

- src/modules/generateQuoteEmbed.ts
> chore: update avatar

- src/modules/generateQuoteEmbed.ts
> chore: update footer

- src/modules/generateQuoteEmbed.ts
> chore: no custom link

- src/modules/generateQuoteEmbed.ts
> chore: update chat link

- src/commands/setup.ts
- src/database/connectDatabase.ts
- src/index.ts
- src/modules/scheduleInspiration.ts
- src/utils/errorHandler.ts
- src/utils/registerCommands.ts
> feat: include avatar and username in webhook
